/**
 * Embed public/* into src/server/embedded-public.ts.
 * Minifies JS/CSS lightly so the single-file binary stays smaller.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative, extname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const outFile = join(root, "src", "server", "embedded-public.ts");

function walk(dir, acc = []) {
  for (const name of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, name.name);
    if (name.isDirectory()) walk(full, acc);
    else acc.push(full);
  }
  return acc;
}

/** Very small CSS minify — safe for our hand-written stylesheet. */
function minifyCss(src) {
  return src
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\s+/g, " ")
    .replace(/\s*([{}:;,>])\s*/g, "$1")
    .replace(/;}/g, "}")
    .trim();
}

/**
 * Light JS minify: strip block comments, line comments, collapse whitespace
 * outside strings. Good enough for our UI script; not a full minifier.
 */
function minifyJs(src) {
  let out = "";
  let i = 0;
  const n = src.length;
  let inStr = null;
  let inLine = false;
  let inBlock = false;
  let prevSpace = false;

  while (i < n) {
    const c = src[i];
    const next = src[i + 1];

    if (inLine) {
      if (c === "\n") {
        inLine = false;
        out += "\n";
        prevSpace = true;
      }
      i++;
      continue;
    }
    if (inBlock) {
      if (c === "*" && next === "/") {
        inBlock = false;
        i += 2;
        continue;
      }
      i++;
      continue;
    }
    if (inStr) {
      out += c;
      if (c === "\\" && i + 1 < n) {
        out += src[i + 1];
        i += 2;
        continue;
      }
      if (c === inStr) inStr = null;
      i++;
      continue;
    }

    if (c === '"' || c === "'" || c === "`") {
      inStr = c;
      out += c;
      prevSpace = false;
      i++;
      continue;
    }
    if (c === "/" && next === "/") {
      inLine = true;
      i += 2;
      continue;
    }
    if (c === "/" && next === "*") {
      inBlock = true;
      i += 2;
      continue;
    }
    if (c === " " || c === "\t" || c === "\n" || c === "\r") {
      if (!prevSpace) {
        out += " ";
        prevSpace = true;
      }
      i++;
      continue;
    }
    out += c;
    prevSpace = false;
    i++;
  }
  return out.replace(/ ?([=+\-*/%<>!?:&|,{}();[\]]) ?/g, "$1").trim();
}

function minifyHtml(src) {
  return src
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/>\s+</g, "><")
    .replace(/\s{2,}/g, " ")
    .trim();
}

const files = walk(publicDir);
const entries = {};
let rawBytes = 0;
let minBytes = 0;

for (const full of files) {
  const rel = relative(publicDir, full).replaceAll("\\", "/");
  const ext = extname(rel).toLowerCase();
  let text = readFileSync(full, "utf8");
  rawBytes += Buffer.byteLength(text);
  if (ext === ".css") text = minifyCss(text);
  else if (ext === ".js") text = minifyJs(text);
  else if (ext === ".html") text = minifyHtml(text);
  minBytes += Buffer.byteLength(text);
  entries[`/${rel}`] = text;
  if (rel === "index.html") {
    entries["/"] = text;
    entries["/index.html"] = text;
  }
}

const body = `/* AUTO-GENERATED by scripts/embed-public.mjs — do not edit */
export const EMBEDDED_PUBLIC: Record<string, string> = ${JSON.stringify(entries)};

export function embeddedContentType(path: string): string {
  const lower = path.toLowerCase();
  if (lower.endsWith(".html") || path === "/") return "text/html; charset=utf-8";
  if (lower.endsWith(".js")) return "application/javascript; charset=utf-8";
  if (lower.endsWith(".css")) return "text/css; charset=utf-8";
  if (lower.endsWith(".json")) return "application/json; charset=utf-8";
  if (lower.endsWith(".svg")) return "image/svg+xml";
  return "application/octet-stream";
}

export function getEmbeddedAsset(path: string): string | null {
  if (EMBEDDED_PUBLIC[path] != null) return EMBEDDED_PUBLIC[path];
  const clean = (path.split("?")[0] || "/");
  if (EMBEDDED_PUBLIC[clean] != null) return EMBEDDED_PUBLIC[clean];
  if (!clean.startsWith("/")) {
    const withSlash = "/" + clean;
    if (EMBEDDED_PUBLIC[withSlash] != null) return EMBEDDED_PUBLIC[withSlash];
  }
  return null;
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body, "utf8");
console.log(
  `embedded ${Object.keys(entries).length} paths -> ${relative(root, outFile)} (${rawBytes} → ${minBytes} bytes UI)`,
);
